name: Event Workflow

on:
  push:
    branches:
      - moiz_branch
  pull_request:
    branches:
      - moiz_branch

jobs:
  Quality_Check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Installing black
      run: pip install black
      
    - name: Installing flake8
      run: pip install flake8
      
    - name: Black check
      run: black main.py
    
    - name: Flake8 check
      run: flake8 --ignore=E501,W503,W293,W291 main.py
      
      
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start app
      run: python main_local.py &
      env:
        FLASK_APP: main_local.py

    - name: Wait for app to start
      run: |
        while ! curl http://127.0.0.1:8080; do
          sleep 1
        done

    - name: Check app status
      run: |
        if curl -I http://127.0.0.1:8080 | grep -q 'HTTP/1.1 200 OK'; then
          echo 'App is running'
        else
          echo 'App is not running'
          exit 1
        fi
