name: Run main.py with linting

on:
  push:
    branches:
      - saads_branch

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: |
          pylint --fail-under=9 main.py
        continue-on-error: true

      - name: Run black
        run: |
          black --check .
        continue-on-error: true

      - name: Run main.py
        run: python main.py
