name: Event Workflow

on:
  push:
    branches:
      - moiz_branch
  pull_request:
    branches:
      - moiz_branch

jobs:
  Quality_Check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Installing black
      run: pip install black
      
    - name: Installing flake8
      run: pip install flake8
      
    - name: Black check
      run: black main.py
    
    - name: Flake8 check
      run: flake8 --ignore=E501,W503,W293,W291 main.py
      
      
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set environment variable
      run: |
        export CLOUD_STORAGE_BUCKET=my_bucket

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: python main.py
