name: Test code

on: [push, pull_request]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Run pylint
        continue-on-error: true
        run: pylint main.py
