name: Push Event Workflow

on: push

jobs:
  Quality_Check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Installing black
      run: pip install black
      
    - name: Installing flake8
      run: pip install flake8
      
    - name: Black check
      run: black main.py
    
    - name: Flake8 check
      run: flake8 --ignore=E501,W503,W293,W291 main.py
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: App running check
      run: Python main.py 
