name: Event Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Quality_Check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Installing black
      run: pip install black
      
    - name: Installing flake8
      run: pip install flake8
      
    - name: Black check
      run: black main.py
    
    - name: Flake8 check
      run: flake8 --ignore=E501,W503,W293,W291 main.py
      
